var dir_7d8eefb3020a6ad35dbc8d18926b9c77 =
[
    [ "bases", "dir_d8fd8f06fa29eac18e0901da131b1081.html", "dir_d8fd8f06fa29eac18e0901da131b1081" ],
    [ "detail", "dir_4c51ee7c33aecbb3be7142e96779c427.html", "dir_4c51ee7c33aecbb3be7142e96779c427" ],
    [ "adjacent_edges.h", "mesh_2components_2adjacent__edges_8h_source.html", null ],
    [ "adjacent_faces.h", "mesh_2components_2adjacent__faces_8h_source.html", null ],
    [ "adjacent_vertices.h", "mesh_2components_2adjacent__vertices_8h_source.html", null ],
    [ "bit_flags.h", "mesh_2components_2bit__flags_8h_source.html", null ],
    [ "bounding_box.h", "mesh_2components_2bounding__box_8h_source.html", null ],
    [ "color.h", "mesh_2components_2color_8h_source.html", null ],
    [ "custom_components.h", "mesh_2components_2custom__components_8h_source.html", null ],
    [ "mark.h", "mesh_2components_2mark_8h_source.html", null ],
    [ "name.h", "mesh_2components_2name_8h_source.html", null ],
    [ "normal.h", "mesh_2components_2normal_8h_source.html", null ],
    [ "parent_mesh_pointer.h", "parent__mesh__pointer_8h_source.html", null ],
    [ "polygon_bit_flags.h", "polygon__bit__flags_8h_source.html", null ],
    [ "position.h", "mesh_2components_2position_8h_source.html", null ],
    [ "principal_curvature.h", "mesh_2components_2principal__curvature_8h_source.html", null ],
    [ "quality.h", "mesh_2components_2quality_8h_source.html", null ],
    [ "tex_coord.h", "mesh_2components_2tex__coord_8h_source.html", null ],
    [ "texture_images.h", "mesh_2components_2texture__images_8h_source.html", null ],
    [ "texture_paths.h", "mesh_2components_2texture__paths_8h_source.html", null ],
    [ "transform_matrix.h", "mesh_2components_2transform__matrix_8h_source.html", null ],
    [ "triangle_bit_flags.h", "triangle__bit__flags_8h_source.html", null ],
    [ "vertex_references.h", "mesh_2components_2vertex__references_8h_source.html", null ],
    [ "wedge_colors.h", "mesh_2components_2wedge__colors_8h_source.html", null ],
    [ "wedge_tex_coords.h", "mesh_2components_2wedge__tex__coords_8h_source.html", null ]
];