var dir_7d8eefb3020a6ad35dbc8d18926b9c77 =
[
    [ "base", "dir_adf091642dbec205bf405f0ed4e816a6.html", "dir_adf091642dbec205bf405f0ed4e816a6" ],
    [ "concepts", "dir_5263b1fbea0747b7739eb9a4840b1ed8.html", "dir_5263b1fbea0747b7739eb9a4840b1ed8" ],
    [ "detail", "dir_4c51ee7c33aecbb3be7142e96779c427.html", "dir_4c51ee7c33aecbb3be7142e96779c427" ],
    [ "adjacent_edges.h", "adjacent__edges_8h_source.html", null ],
    [ "adjacent_faces.h", "adjacent__faces_8h_source.html", null ],
    [ "adjacent_vertices.h", "adjacent__vertices_8h_source.html", null ],
    [ "bit_flags.h", "bit__flags_8h_source.html", null ],
    [ "bounding_box.h", "mesh_2components_2bounding__box_8h_source.html", null ],
    [ "color.h", "mesh_2components_2color_8h_source.html", null ],
    [ "custom_components.h", "custom__components_8h_source.html", null ],
    [ "mark.h", "mark_8h_source.html", null ],
    [ "name.h", "name_8h_source.html", null ],
    [ "normal.h", "mesh_2components_2normal_8h_source.html", null ],
    [ "parent_mesh_pointer.h", "parent__mesh__pointer_8h_source.html", null ],
    [ "polygon_bit_flags.h", "polygon__bit__flags_8h_source.html", null ],
    [ "position.h", "position_8h_source.html", null ],
    [ "principal_curvature.h", "mesh_2components_2principal__curvature_8h_source.html", null ],
    [ "quality.h", "mesh_2components_2quality_8h_source.html", null ],
    [ "tex_coord.h", "mesh_2components_2tex__coord_8h_source.html", null ],
    [ "texture_images.h", "texture__images_8h_source.html", null ],
    [ "texture_paths.h", "texture__paths_8h_source.html", null ],
    [ "transform_matrix.h", "transform__matrix_8h_source.html", null ],
    [ "triangle_bit_flags.h", "triangle__bit__flags_8h_source.html", null ],
    [ "vertex_references.h", "vertex__references_8h_source.html", null ],
    [ "wedge_colors.h", "wedge__colors_8h_source.html", null ],
    [ "wedge_tex_coords.h", "wedge__tex__coords_8h_source.html", null ]
];