var annotated_dup =
[
    [ "vcl", null, [
      [ "comp", null, [
        [ "AdjacentEdges", "classvcl_1_1comp_1_1AdjacentEdges.html", "classvcl_1_1comp_1_1AdjacentEdges" ],
        [ "AdjacentFaces", "classvcl_1_1comp_1_1AdjacentFaces.html", "classvcl_1_1comp_1_1AdjacentFaces" ],
        [ "AdjacentVertices", "classvcl_1_1comp_1_1AdjacentVertices.html", "classvcl_1_1comp_1_1AdjacentVertices" ],
        [ "BitFlags", "classvcl_1_1comp_1_1BitFlags.html", "classvcl_1_1comp_1_1BitFlags" ],
        [ "BoundingBox", "classvcl_1_1comp_1_1BoundingBox.html", "classvcl_1_1comp_1_1BoundingBox" ],
        [ "Color", "classvcl_1_1comp_1_1Color.html", "classvcl_1_1comp_1_1Color" ],
        [ "Component", "classvcl_1_1comp_1_1Component.html", "classvcl_1_1comp_1_1Component" ],
        [ "ContainerComponent", "classvcl_1_1comp_1_1ContainerComponent.html", "classvcl_1_1comp_1_1ContainerComponent" ],
        [ "Coordinate", "classvcl_1_1comp_1_1Coordinate.html", "classvcl_1_1comp_1_1Coordinate" ],
        [ "CustomComponents", "classvcl_1_1comp_1_1CustomComponents.html", "classvcl_1_1comp_1_1CustomComponents" ],
        [ "IndexContainerComponent", "classvcl_1_1comp_1_1IndexContainerComponent.html", "classvcl_1_1comp_1_1IndexContainerComponent" ],
        [ "IsComponentPred", "structvcl_1_1comp_1_1IsComponentPred.html", null ],
        [ "IsVerticalComponentPred", "structvcl_1_1comp_1_1IsVerticalComponentPred.html", null ],
        [ "Mark", "classvcl_1_1comp_1_1Mark.html", "classvcl_1_1comp_1_1Mark" ],
        [ "Name", "classvcl_1_1comp_1_1Name.html", "classvcl_1_1comp_1_1Name" ],
        [ "Normal", "classvcl_1_1comp_1_1Normal.html", "classvcl_1_1comp_1_1Normal" ],
        [ "ParentMeshPointer", "classvcl_1_1comp_1_1ParentMeshPointer.html", null ],
        [ "PointerContainerComponent", "classvcl_1_1comp_1_1PointerContainerComponent.html", "classvcl_1_1comp_1_1PointerContainerComponent" ],
        [ "PolygonBitFlags", "classvcl_1_1comp_1_1PolygonBitFlags.html", "classvcl_1_1comp_1_1PolygonBitFlags" ],
        [ "PrincipalCurvature", "classvcl_1_1comp_1_1PrincipalCurvature.html", "classvcl_1_1comp_1_1PrincipalCurvature" ],
        [ "Quality", "classvcl_1_1comp_1_1Quality.html", "classvcl_1_1comp_1_1Quality" ],
        [ "ReferenceContainerComponent", "classvcl_1_1comp_1_1ReferenceContainerComponent.html", null ],
        [ "ReferencesComponentTriggerer", "classvcl_1_1comp_1_1ReferencesComponentTriggerer.html", null ],
        [ "TexCoord", "classvcl_1_1comp_1_1TexCoord.html", "classvcl_1_1comp_1_1TexCoord" ],
        [ "TextureImages", "classvcl_1_1comp_1_1TextureImages.html", "classvcl_1_1comp_1_1TextureImages" ],
        [ "TexturePaths", "classvcl_1_1comp_1_1TexturePaths.html", "classvcl_1_1comp_1_1TexturePaths" ],
        [ "TransformMatrix", "classvcl_1_1comp_1_1TransformMatrix.html", "classvcl_1_1comp_1_1TransformMatrix" ],
        [ "TriangleBitFlags", "classvcl_1_1comp_1_1TriangleBitFlags.html", "classvcl_1_1comp_1_1TriangleBitFlags" ],
        [ "VertexReferences", "classvcl_1_1comp_1_1VertexReferences.html", "classvcl_1_1comp_1_1VertexReferences" ],
        [ "WedgeColors", "classvcl_1_1comp_1_1WedgeColors.html", "classvcl_1_1comp_1_1WedgeColors" ],
        [ "WedgeTexCoords", "classvcl_1_1comp_1_1WedgeTexCoords.html", "classvcl_1_1comp_1_1WedgeTexCoords" ]
      ] ],
      [ "edgemesh", null, [
        [ "Edge", "classvcl_1_1edgemesh_1_1Edge.html", null ],
        [ "Vertex", "classvcl_1_1edgemesh_1_1Vertex.html", null ]
      ] ],
      [ "glfw", null, [
        [ "WindowManager", "classvcl_1_1glfw_1_1WindowManager.html", "classvcl_1_1glfw_1_1WindowManager" ]
      ] ],
      [ "imgui", null, [
        [ "ImGuiDrawer", "classvcl_1_1imgui_1_1ImGuiDrawer.html", null ]
      ] ],
      [ "mesh", null, [
        [ "ContainerOfElement", "structvcl_1_1mesh_1_1ContainerOfElement.html", null ],
        [ "CustomComponentsVectorMap", "classvcl_1_1mesh_1_1CustomComponentsVectorMap.html", null ],
        [ "CustomComponentsVectorMap< true >", "classvcl_1_1mesh_1_1CustomComponentsVectorMap_3_01true_01_4.html", "classvcl_1_1mesh_1_1CustomComponentsVectorMap_3_01true_01_4" ],
        [ "EdgeContainer", "classvcl_1_1mesh_1_1EdgeContainer.html", "classvcl_1_1mesh_1_1EdgeContainer" ],
        [ "ElementContainer", "classvcl_1_1mesh_1_1ElementContainer.html", "classvcl_1_1mesh_1_1ElementContainer" ],
        [ "ElementContainerTriggerer", "classvcl_1_1mesh_1_1ElementContainerTriggerer.html", null ],
        [ "FaceContainer", "classvcl_1_1mesh_1_1FaceContainer.html", "classvcl_1_1mesh_1_1FaceContainer" ],
        [ "HasContainerOfElementPred", "structvcl_1_1mesh_1_1HasContainerOfElementPred.html", null ],
        [ "HasContainerOfPred", "structvcl_1_1mesh_1_1HasContainerOfPred.html", null ],
        [ "IsElementContainerPred", "structvcl_1_1mesh_1_1IsElementContainerPred.html", null ],
        [ "VertexContainer", "classvcl_1_1mesh_1_1VertexContainer.html", "classvcl_1_1mesh_1_1VertexContainer" ],
        [ "VerticalComponentsVectorTuple", "classvcl_1_1mesh_1_1VerticalComponentsVectorTuple.html", null ],
        [ "VerticalComponentsVectorTuple< TypeWrapper< Comp... > >", "classvcl_1_1mesh_1_1VerticalComponentsVectorTuple_3_01TypeWrapper_3_01Comp_8_8_8_01_4_01_4.html", null ]
      ] ],
      [ "pointcloud", null, [
        [ "Vertex", "classvcl_1_1pointcloud_1_1Vertex.html", null ]
      ] ],
      [ "polyedgemesh", null, [
        [ "Edge", "classvcl_1_1polyedgemesh_1_1Edge.html", null ],
        [ "Face", "classvcl_1_1polyedgemesh_1_1Face.html", null ],
        [ "Vertex", "classvcl_1_1polyedgemesh_1_1Vertex.html", null ]
      ] ],
      [ "polymesh", null, [
        [ "Face", "classvcl_1_1polymesh_1_1Face.html", null ],
        [ "Vertex", "classvcl_1_1polymesh_1_1Vertex.html", null ]
      ] ],
      [ "qt", null, [
        [ "ActionFileDialog", "classvcl_1_1qt_1_1ActionFileDialog.html", "classvcl_1_1qt_1_1ActionFileDialog" ],
        [ "BoolParameterRow", "classvcl_1_1qt_1_1BoolParameterRow.html", null ],
        [ "DebugIODevice", "classvcl_1_1qt_1_1DebugIODevice.html", null ],
        [ "DrawableObjectFrame", "classvcl_1_1qt_1_1DrawableObjectFrame.html", null ],
        [ "DrawableObjectVectorFrame", "classvcl_1_1qt_1_1DrawableObjectVectorFrame.html", null ],
        [ "EdgesFrame", "classvcl_1_1qt_1_1EdgesFrame.html", null ],
        [ "EnumParameterRow", "classvcl_1_1qt_1_1EnumParameterRow.html", null ],
        [ "ErrorIODevice", "classvcl_1_1qt_1_1ErrorIODevice.html", null ],
        [ "FilterMeshDockWidget", "classvcl_1_1qt_1_1FilterMeshDockWidget.html", null ],
        [ "GenericMeshRenderSettingsFrame", "classvcl_1_1qt_1_1GenericMeshRenderSettingsFrame.html", null ],
        [ "MeshProcessingMainWindow", "classvcl_1_1qt_1_1MeshProcessingMainWindow.html", null ],
        [ "MeshRenderSettingsFrame", "classvcl_1_1qt_1_1MeshRenderSettingsFrame.html", null ],
        [ "MeshViewer", "classvcl_1_1qt_1_1MeshViewer.html", "classvcl_1_1qt_1_1MeshViewer" ],
        [ "MessageHider", "classvcl_1_1qt_1_1MessageHider.html", null ],
        [ "MessageIODevice", "classvcl_1_1qt_1_1MessageIODevice.html", null ],
        [ "MultiParameterFrame", "classvcl_1_1qt_1_1MultiParameterFrame.html", null ],
        [ "ParameterFrame", "classvcl_1_1qt_1_1ParameterFrame.html", null ],
        [ "ParameterRow", "classvcl_1_1qt_1_1ParameterRow.html", null ],
        [ "ParametersGridLayout", "classvcl_1_1qt_1_1ParametersGridLayout.html", null ],
        [ "ParameterSubFrame", "classvcl_1_1qt_1_1ParameterSubFrame.html", null ],
        [ "PointsFrame", "classvcl_1_1qt_1_1PointsFrame.html", null ],
        [ "QClickableLabel", "classvcl_1_1qt_1_1QClickableLabel.html", null ],
        [ "ScalarParameterRow", "classvcl_1_1qt_1_1ScalarParameterRow.html", null ],
        [ "ScreenShotDialog", "classvcl_1_1qt_1_1ScreenShotDialog.html", null ],
        [ "SurfaceFrame", "classvcl_1_1qt_1_1SurfaceFrame.html", null ],
        [ "TextEditLogger", "classvcl_1_1qt_1_1TextEditLogger.html", "classvcl_1_1qt_1_1TextEditLogger" ],
        [ "UintParameterRow", "classvcl_1_1qt_1_1UintParameterRow.html", null ],
        [ "UscalarParameterRow", "classvcl_1_1qt_1_1UscalarParameterRow.html", null ],
        [ "WarningIODevice", "classvcl_1_1qt_1_1WarningIODevice.html", null ],
        [ "WidgetManager", "classvcl_1_1qt_1_1WidgetManager.html", "classvcl_1_1qt_1_1WidgetManager" ],
        [ "WireframeFrame", "classvcl_1_1qt_1_1WireframeFrame.html", null ]
      ] ],
      [ "triedgemesh", null, [
        [ "Edge", "classvcl_1_1triedgemesh_1_1Edge.html", null ],
        [ "Face", "classvcl_1_1triedgemesh_1_1Face.html", null ],
        [ "Vertex", "classvcl_1_1triedgemesh_1_1Vertex.html", null ]
      ] ],
      [ "trimesh", null, [
        [ "Face", "classvcl_1_1trimesh_1_1Face.html", null ],
        [ "Vertex", "classvcl_1_1trimesh_1_1Vertex.html", null ]
      ] ],
      [ "AbstractDrawableMesh", "classvcl_1_1AbstractDrawableMesh.html", "classvcl_1_1AbstractDrawableMesh" ],
      [ "AbstractGrid", "classvcl_1_1AbstractGrid.html", "classvcl_1_1AbstractGrid" ],
      [ "AbstractLogger", "classvcl_1_1AbstractLogger.html", "classvcl_1_1AbstractLogger" ],
      [ "AbstractViewerDrawer", "classvcl_1_1AbstractViewerDrawer.html", null ],
      [ "Array", "classvcl_1_1Array.html", "classvcl_1_1Array" ],
      [ "BadCustomComponentTypeException", "classvcl_1_1BadCustomComponentTypeException.html", null ],
      [ "BadVertexIndexException", "classvcl_1_1BadVertexIndexException.html", null ],
      [ "BipartiteGraph", "classvcl_1_1BipartiteGraph.html", "classvcl_1_1BipartiteGraph" ],
      [ "BitProxy", "classvcl_1_1BitProxy.html", "classvcl_1_1BitProxy" ],
      [ "BitSet", "classvcl_1_1BitSet.html", "classvcl_1_1BitSet" ],
      [ "BlockerEventDrawer", "classvcl_1_1BlockerEventDrawer.html", null ],
      [ "Box", "classvcl_1_1Box.html", "classvcl_1_1Box" ],
      [ "Callback", "classvcl_1_1Callback.html", null ],
      [ "Camera", "classvcl_1_1Camera.html", "classvcl_1_1Camera" ],
      [ "CameraUniforms", "classvcl_1_1CameraUniforms.html", null ],
      [ "CannotOpenFileException", "classvcl_1_1CannotOpenFileException.html", null ],
      [ "CanvasBGFX", "classvcl_1_1CanvasBGFX.html", "classvcl_1_1CanvasBGFX" ],
      [ "CanvasOpenGL2", "classvcl_1_1CanvasOpenGL2.html", "classvcl_1_1CanvasOpenGL2" ],
      [ "CellIterator", "classvcl_1_1CellIterator.html", null ],
      [ "Color", "classvcl_1_1Color.html", "classvcl_1_1Color" ],
      [ "CompId", "structvcl_1_1CompId.html", null ],
      [ "ComponentString", "structvcl_1_1ComponentString.html", "structvcl_1_1ComponentString" ],
      [ "ConsoleLogger", "classvcl_1_1ConsoleLogger.html", null ],
      [ "ConstMeshEdgeUtil", "classvcl_1_1ConstMeshEdgeUtil.html", null ],
      [ "ConstPointerIterator", "classvcl_1_1ConstPointerIterator.html", null ],
      [ "ConstStaticGridIterator", "classvcl_1_1ConstStaticGridIterator.html", null ],
      [ "Context", "classvcl_1_1Context.html", "classvcl_1_1Context" ],
      [ "CreateSphereArgs", "structvcl_1_1CreateSphereArgs.html", null ],
      [ "CustomComponentVectorHandle", "classvcl_1_1CustomComponentVectorHandle.html", "classvcl_1_1CustomComponentVectorHandle" ],
      [ "DesktopTrackBall", "classvcl_1_1DesktopTrackBall.html", null ],
      [ "DirectionalLight", "classvcl_1_1DirectionalLight.html", null ],
      [ "DirectionalLightUniforms", "classvcl_1_1DirectionalLightUniforms.html", "classvcl_1_1DirectionalLightUniforms" ],
      [ "Distribution", "classvcl_1_1Distribution.html", "classvcl_1_1Distribution" ],
      [ "DrawableAxis", "classvcl_1_1DrawableAxis.html", "classvcl_1_1DrawableAxis" ],
      [ "DrawableAxisUniforms", "classvcl_1_1DrawableAxisUniforms.html", null ],
      [ "DrawableDirectionalLight", "classvcl_1_1DrawableDirectionalLight.html", "classvcl_1_1DrawableDirectionalLight" ],
      [ "DrawableDirectionalLightUniforms", "classvcl_1_1DrawableDirectionalLightUniforms.html", null ],
      [ "DrawableMeshBGFX", "classvcl_1_1DrawableMeshBGFX.html", "classvcl_1_1DrawableMeshBGFX" ],
      [ "DrawableMeshOpenGL2", "classvcl_1_1DrawableMeshOpenGL2.html", "classvcl_1_1DrawableMeshOpenGL2" ],
      [ "DrawableMeshUniforms", "classvcl_1_1DrawableMeshUniforms.html", null ],
      [ "DrawableObject", "classvcl_1_1DrawableObject.html", "classvcl_1_1DrawableObject" ],
      [ "DrawableObjectVector", "classvcl_1_1DrawableObjectVector.html", "classvcl_1_1DrawableObjectVector" ],
      [ "DrawableTrackBall", "classvcl_1_1DrawableTrackBall.html", "classvcl_1_1DrawableTrackBall" ],
      [ "DrawableTrackballUniforms", "classvcl_1_1DrawableTrackballUniforms.html", null ],
      [ "Edge", "classvcl_1_1Edge.html", "classvcl_1_1Edge" ],
      [ "Edge< MeshType, TypeWrapper< Comps... > >", "classvcl_1_1Edge_3_01MeshType_00_01TypeWrapper_3_01Comps_8_8_8_01_4_01_4.html", null ],
      [ "EdgeAdjFaceIterator", "classvcl_1_1EdgeAdjFaceIterator.html", null ],
      [ "EdgeMeshT", "classvcl_1_1EdgeMeshT.html", null ],
      [ "Element", "classvcl_1_1Element.html", "classvcl_1_1Element" ],
      [ "ElementContainerIterator", "classvcl_1_1ElementContainerIterator.html", "classvcl_1_1ElementContainerIterator" ],
      [ "ElementString", "structvcl_1_1ElementString.html", "structvcl_1_1ElementString" ],
      [ "ElemId", "structvcl_1_1ElemId.html", null ],
      [ "EmbeddedFont", "structvcl_1_1EmbeddedFont.html", null ],
      [ "EmbeddedFont< VclFont::DROID_SANS >", "structvcl_1_1EmbeddedFont_3_01VclFont_1_1DROID__SANS_01_4.html", null ],
      [ "EmbeddedShader", "structvcl_1_1EmbeddedShader.html", null ],
      [ "EmbeddedShader< VclProgram::DRAWABLE_AXIS >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1DRAWABLE__AXIS_01_4.html", null ],
      [ "EmbeddedShader< VclProgram::DRAWABLE_DIRECTIONAL_LIGHT >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1DRAWABLE__DIRECTIONAL__LIGHT_01_4.html", null ],
      [ "EmbeddedShader< VclProgram::DRAWABLE_MESH >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1DRAWABLE__MESH_01_4.html", null ],
      [ "EmbeddedShader< VclProgram::DRAWABLE_TRACKBALL >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1DRAWABLE__TRACKBALL_01_4.html", null ],
      [ "EmbeddedShader< VclProgram::FONT_BASIC >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1FONT__BASIC_01_4.html", null ],
      [ "EmbeddedShader< VclProgram::FONT_DISTANCE_FIELD >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1FONT__DISTANCE__FIELD_01_4.html", null ],
      [ "EmbeddedShader< VclProgram::FONT_DISTANCE_FIELD_DROP_SHADOW >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1FONT__DISTANCE__FIELD__DROP__SHADOW_01_4.html", null ],
      [ "EmbeddedShader< VclProgram::FONT_DISTANCE_FIELD_DROP_SHADOW_IMAGE >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1FONT__DISTANCE__FIELD__DROP__SHADOW__IMAGE_01_4.html", null ],
      [ "EmbeddedShader< VclProgram::FONT_DISTANCE_FIELD_OUTLINE >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1FONT__DISTANCE__FIELD__OUTLINE_01_4.html", null ],
      [ "EmbeddedShader< VclProgram::FONT_DISTANCE_FIELD_OUTLINE_DROP_SHADOW_IMAGE >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1FONT__DISTANCE__FIELD__OUTLINE__DROP__SHADOW__IMAGE_01_4.html", null ],
      [ "EmbeddedShader< VclProgram::FONT_DISTANCE_FIELD_OUTLINE_IMAGE >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1FONT__DISTANCE__FIELD__OUTLINE__IMAGE_01_4.html", null ],
      [ "EmbeddedShader< VclProgram::FONT_DISTANCE_FIELD_SUBPIXEL >", "structvcl_1_1EmbeddedShader_3_01VclProgram_1_1FONT__DISTANCE__FIELD__SUBPIXEL_01_4.html", null ],
      [ "EventDrawer", "classvcl_1_1EventDrawer.html", null ],
      [ "Face", "classvcl_1_1Face.html", "classvcl_1_1Face" ],
      [ "Face< MeshType, TypeWrapper< Comps... > >", "classvcl_1_1Face_3_01MeshType_00_01TypeWrapper_3_01Comps_8_8_8_01_4_01_4.html", null ],
      [ "FakePointerWithValue", "classvcl_1_1FakePointerWithValue.html", null ],
      [ "FileFormat", "classvcl_1_1FileFormat.html", "classvcl_1_1FileFormat" ],
      [ "FileInfo", "classvcl_1_1FileInfo.html", "classvcl_1_1FileInfo" ],
      [ "FileType", "structvcl_1_1FileType.html", "structvcl_1_1FileType" ],
      [ "FilterTypesByCondition", "structvcl_1_1FilterTypesByCondition.html", null ],
      [ "FilterTypesByCondition< Pred, Head, Tail... >", "structvcl_1_1FilterTypesByCondition_3_01Pred_00_01Head_00_01Tail_8_8_8_01_4.html", null ],
      [ "FilterTypesByCondition< Pred, TypeWrapper< Tail... > >", "structvcl_1_1FilterTypesByCondition_3_01Pred_00_01TypeWrapper_3_01Tail_8_8_8_01_4_01_4.html", null ],
      [ "FirstElementPairComparator", "structvcl_1_1FirstElementPairComparator.html", null ],
      [ "FirstRefPair", "classvcl_1_1FirstRefPair.html", null ],
      [ "FirstType", "structvcl_1_1FirstType.html", null ],
      [ "FirstType< TypeWrapper< Args... > >", "structvcl_1_1FirstType_3_01TypeWrapper_3_01Args_8_8_8_01_4_01_4.html", null ],
      [ "FontData", "structvcl_1_1FontData.html", null ],
      [ "FontManager", "classvcl_1_1FontManager.html", null ],
      [ "ForEachType", "structvcl_1_1ForEachType.html", null ],
      [ "ForEachType< TypeWrapper< T... > >", "structvcl_1_1ForEachType_3_01TypeWrapper_3_01T_8_8_8_01_4_01_4.html", null ],
      [ "GetTypeByCondition", "structvcl_1_1GetTypeByCondition.html", null ],
      [ "GetTypeByCondition< Pred, TypeWrapper< Args... > >", "structvcl_1_1GetTypeByCondition_3_01Pred_00_01TypeWrapper_3_01Args_8_8_8_01_4_01_4.html", null ],
      [ "HashTableGrid", "classvcl_1_1HashTableGrid.html", "classvcl_1_1HashTableGrid" ],
      [ "HausdorffDistResult", "structvcl_1_1HausdorffDistResult.html", null ],
      [ "Histogram", "classvcl_1_1Histogram.html", "classvcl_1_1Histogram" ],
      [ "Image", "classvcl_1_1Image.html", "classvcl_1_1Image" ],
      [ "ImGuiShaders", "structvcl_1_1ImGuiShaders.html", null ],
      [ "InconsistentMeshException", "classvcl_1_1InconsistentMeshException.html", null ],
      [ "IndexBuffer", "classvcl_1_1IndexBuffer.html", "classvcl_1_1IndexBuffer" ],
      [ "IndexFromPointerIterator", "classvcl_1_1IndexFromPointerIterator.html", null ],
      [ "IndexInTypes", "structvcl_1_1IndexInTypes.html", null ],
      [ "IndexInTypes< T, TypeWrapper< Us... > >", "structvcl_1_1IndexInTypes_3_01T_00_01TypeWrapper_3_01Us_8_8_8_01_4_01_4.html", null ],
      [ "KDTree", "classvcl_1_1KDTree.html", "classvcl_1_1KDTree" ],
      [ "Key", "structvcl_1_1Key.html", null ],
      [ "KeyModifier", "structvcl_1_1KeyModifier.html", null ],
      [ "KeyRefValueRefPair", "classvcl_1_1KeyRefValueRefPair.html", null ],
      [ "KeyValueRefPair", "classvcl_1_1KeyValueRefPair.html", null ],
      [ "LoadSettings", "structvcl_1_1LoadSettings.html", "structvcl_1_1LoadSettings" ],
      [ "Logger", "classvcl_1_1Logger.html", "classvcl_1_1Logger" ],
      [ "MakeConstPointer", "structvcl_1_1MakeConstPointer.html", null ],
      [ "MakeConstPointer< T * >", "structvcl_1_1MakeConstPointer_3_01T_01_5_01_4.html", null ],
      [ "MalformedFileException", "classvcl_1_1MalformedFileException.html", null ],
      [ "Matrix", "classvcl_1_1Matrix.html", null ],
      [ "Mesh", "classvcl_1_1Mesh.html", "classvcl_1_1Mesh" ],
      [ "MeshEdgeUtil", "classvcl_1_1MeshEdgeUtil.html", null ],
      [ "MeshInertia", "classvcl_1_1MeshInertia.html", "classvcl_1_1MeshInertia" ],
      [ "MeshInfo", "classvcl_1_1MeshInfo.html", "classvcl_1_1MeshInfo" ],
      [ "MeshPos", "classvcl_1_1MeshPos.html", "classvcl_1_1MeshPos" ],
      [ "MeshRenderBuffers", "classvcl_1_1MeshRenderBuffers.html", null ],
      [ "MeshRenderData", "classvcl_1_1MeshRenderData.html", null ],
      [ "MeshRenderSettings", "classvcl_1_1MeshRenderSettings.html", "classvcl_1_1MeshRenderSettings" ],
      [ "MeshRenderSettingsUniforms", "classvcl_1_1MeshRenderSettingsUniforms.html", null ],
      [ "MeshSampler", "classvcl_1_1MeshSampler.html", null ],
      [ "MissingCompactnessException", "classvcl_1_1MissingCompactnessException.html", null ],
      [ "MissingComponentException", "classvcl_1_1MissingComponentException.html", null ],
      [ "MissingPreconditionException", "classvcl_1_1MissingPreconditionException.html", null ],
      [ "MissingQuadRequirementException", "classvcl_1_1MissingQuadRequirementException.html", null ],
      [ "MissingTriangularRequirementException", "classvcl_1_1MissingTriangularRequirementException.html", null ],
      [ "MouseButton", "structvcl_1_1MouseButton.html", null ],
      [ "NestedInitializerListsProcessor", "classvcl_1_1NestedInitializerListsProcessor.html", "classvcl_1_1NestedInitializerListsProcessor" ],
      [ "NestedInitializerListsProcessor< T, 1 >", "classvcl_1_1NestedInitializerListsProcessor_3_01T_00_011_01_4.html", null ],
      [ "NodeIterator", "classvcl_1_1NodeIterator.html", null ],
      [ "NoIntersectionException", "classvcl_1_1NoIntersectionException.html", null ],
      [ "NullLogger", "classvcl_1_1NullLogger.html", "classvcl_1_1NullLogger" ],
      [ "NumberOfTypes", "structvcl_1_1NumberOfTypes.html", null ],
      [ "NumberOfTypes< TypeWrapper< Args... > >", "structvcl_1_1NumberOfTypes_3_01TypeWrapper_3_01Args_8_8_8_01_4_01_4.html", null ],
      [ "PairComparator", "structvcl_1_1PairComparator.html", null ],
      [ "PlainDrawer", "classvcl_1_1PlainDrawer.html", null ],
      [ "Plane", "classvcl_1_1Plane.html", "classvcl_1_1Plane" ],
      [ "Point", "classvcl_1_1Point.html", "classvcl_1_1Point" ],
      [ "PointCloudT", "classvcl_1_1PointCloudT.html", null ],
      [ "PointerFromIndexIterator", "classvcl_1_1PointerFromIndexIterator.html", "classvcl_1_1PointerFromIndexIterator" ],
      [ "PointerVector", "classvcl_1_1PointerVector.html", "classvcl_1_1PointerVector" ],
      [ "PointSampler", "classvcl_1_1PointSampler.html", null ],
      [ "PolyEdgeMeshT", "classvcl_1_1PolyEdgeMeshT.html", null ],
      [ "Polygon", "classvcl_1_1Polygon.html", "classvcl_1_1Polygon" ],
      [ "PolyMeshT", "classvcl_1_1PolyMeshT.html", null ],
      [ "PolymorphicObjectVector", "classvcl_1_1PolymorphicObjectVector.html", "classvcl_1_1PolymorphicObjectVector" ],
      [ "PrincipalCurvature", "classvcl_1_1PrincipalCurvature.html", "classvcl_1_1PrincipalCurvature" ],
      [ "ProgramManager", "classvcl_1_1ProgramManager.html", null ],
      [ "Quaternion", "classvcl_1_1Quaternion.html", "classvcl_1_1Quaternion" ],
      [ "ReadBufferTypes", "structvcl_1_1ReadBufferTypes.html", null ],
      [ "RefPair", "classvcl_1_1RefPair.html", null ],
      [ "RegularGrid", "classvcl_1_1RegularGrid.html", "classvcl_1_1RegularGrid" ],
      [ "RenderApp", "classvcl_1_1RenderApp.html", "classvcl_1_1RenderApp" ],
      [ "SaveSettings", "structvcl_1_1SaveSettings.html", "structvcl_1_1SaveSettings" ],
      [ "SecondRefPair", "classvcl_1_1SecondRefPair.html", null ],
      [ "Segment", "classvcl_1_1Segment.html", "classvcl_1_1Segment" ],
      [ "Sphere", "classvcl_1_1Sphere.html", "classvcl_1_1Sphere" ],
      [ "StaticGrid", "classvcl_1_1StaticGrid.html", null ],
      [ "StaticGridIterator", "classvcl_1_1StaticGridIterator.html", "classvcl_1_1StaticGridIterator" ],
      [ "TexCoord", "classvcl_1_1TexCoord.html", null ],
      [ "TexCoordIndexed", "classvcl_1_1TexCoordIndexed.html", null ],
      [ "TextDrawer", "classvcl_1_1TextDrawer.html", null ],
      [ "TextManager", "classvcl_1_1TextManager.html", null ],
      [ "Texture", "classvcl_1_1Texture.html", "classvcl_1_1Texture" ],
      [ "TextView", "classvcl_1_1TextView.html", null ],
      [ "Timer", "classvcl_1_1Timer.html", "classvcl_1_1Timer" ],
      [ "Tokenizer", "classvcl_1_1Tokenizer.html", null ],
      [ "TrackBall", "classvcl_1_1TrackBall.html", "classvcl_1_1TrackBall" ],
      [ "Triangle", "classvcl_1_1Triangle.html", "classvcl_1_1Triangle" ],
      [ "TriangleWrapper", "classvcl_1_1TriangleWrapper.html", "classvcl_1_1TriangleWrapper" ],
      [ "TriEdgeMeshT", "classvcl_1_1TriEdgeMeshT.html", null ],
      [ "TriMeshT", "classvcl_1_1TriMeshT.html", null ],
      [ "TriPolyIndexBiMap", "classvcl_1_1TriPolyIndexBiMap.html", "classvcl_1_1TriPolyIndexBiMap" ],
      [ "TypesSatisfyCondition", "structvcl_1_1TypesSatisfyCondition.html", null ],
      [ "TypesSatisfyCondition< Pred, TypeWrapper< Args... > >", "structvcl_1_1TypesSatisfyCondition_3_01Pred_00_01TypeWrapper_3_01Args_8_8_8_01_4_01_4.html", null ],
      [ "TypeWrapper", "structvcl_1_1TypeWrapper.html", null ],
      [ "UndirectedNode", "classvcl_1_1UndirectedNode.html", null ],
      [ "Uniform", "classvcl_1_1Uniform.html", null ],
      [ "UnknownFileFormatException", "classvcl_1_1UnknownFileFormatException.html", null ],
      [ "UnorderedPairComparator", "structvcl_1_1UnorderedPairComparator.html", null ],
      [ "VclFont", "structvcl_1_1VclFont.html", null ],
      [ "VclProgram", "structvcl_1_1VclProgram.html", null ],
      [ "Vector", "classvcl_1_1Vector.html", "classvcl_1_1Vector" ],
      [ "Vertex", "classvcl_1_1Vertex.html", null ],
      [ "Vertex< MeshType, TypeWrapper< Comps... > >", "classvcl_1_1Vertex_3_01MeshType_00_01TypeWrapper_3_01Comps_8_8_8_01_4_01_4.html", "classvcl_1_1Vertex_3_01MeshType_00_01TypeWrapper_3_01Comps_8_8_8_01_4_01_4" ],
      [ "VertexBuffer", "classvcl_1_1VertexBuffer.html", "classvcl_1_1VertexBuffer" ],
      [ "View", "classvcl_1_1View.html", null ],
      [ "ViewerDrawerBGFX", "classvcl_1_1ViewerDrawerBGFX.html", null ],
      [ "ViewerDrawerOpenGL2", "classvcl_1_1ViewerDrawerOpenGL2.html", null ],
      [ "WindowManagerId", "structvcl_1_1WindowManagerId.html", null ],
      [ "WrongSizeException", "classvcl_1_1WrongSizeException.html", null ]
    ] ],
    [ "ImGui_ImplQt_Data", "structImGui__ImplQt__Data.html", null ],
    [ "ImGuiQtEventFilter", "classImGuiQtEventFilter.html", null ],
    [ "OcornutImguiContext", "structOcornutImguiContext.html", null ]
];