var dir_05fc1a9b5efe1a4134a1cd4ab2a96dee =
[
    [ "bases", "dir_0027b492a647bf7873ba5c72d8367f51.html", "dir_0027b492a647bf7873ba5c72d8367f51" ],
    [ "internal", "dir_a3552b51592d5b994fdb08b46965e8e2.html", "dir_a3552b51592d5b994fdb08b46965e8e2" ],
    [ "adjacent_edges.h", "mesh_2components_2adjacent__edges_8h.html", "mesh_2components_2adjacent__edges_8h" ],
    [ "adjacent_faces.h", "mesh_2components_2adjacent__faces_8h.html", "mesh_2components_2adjacent__faces_8h" ],
    [ "adjacent_vertices.h", "mesh_2components_2adjacent__vertices_8h.html", "mesh_2components_2adjacent__vertices_8h" ],
    [ "bit_flags.h", "mesh_2components_2bit__flags_8h.html", null ],
    [ "bounding_box.h", "mesh_2components_2bounding__box_8h.html", "mesh_2components_2bounding__box_8h" ],
    [ "color.h", "mesh_2components_2color_8h.html", "mesh_2components_2color_8h" ],
    [ "coordinate.h", "mesh_2components_2coordinate_8h.html", "mesh_2components_2coordinate_8h" ],
    [ "custom_components.h", "mesh_2components_2custom__components_8h.html", null ],
    [ "mark.h", "mesh_2components_2mark_8h.html", "mesh_2components_2mark_8h" ],
    [ "name.h", "mesh_2components_2name_8h.html", "mesh_2components_2name_8h" ],
    [ "normal.h", "mesh_2components_2normal_8h.html", "mesh_2components_2normal_8h" ],
    [ "parent_mesh_pointer.h", "parent__mesh__pointer_8h.html", null ],
    [ "polygon_bit_flags.h", "polygon__bit__flags_8h.html", null ],
    [ "principal_curvature.h", "mesh_2components_2principal__curvature_8h.html", "mesh_2components_2principal__curvature_8h" ],
    [ "quality.h", "mesh_2components_2quality_8h.html", "mesh_2components_2quality_8h" ],
    [ "tex_coord.h", "mesh_2components_2tex__coord_8h.html", "mesh_2components_2tex__coord_8h" ],
    [ "texture_paths.h", "mesh_2components_2texture__paths_8h.html", null ],
    [ "transform_matrix.h", "mesh_2components_2transform__matrix_8h.html", "mesh_2components_2transform__matrix_8h" ],
    [ "triangle_bit_flags.h", "triangle__bit__flags_8h.html", null ],
    [ "vertex_pointers.h", "mesh_2components_2vertex__pointers_8h.html", null ],
    [ "wedge_colors.h", "mesh_2components_2wedge__colors_8h.html", "mesh_2components_2wedge__colors_8h" ],
    [ "wedge_tex_coords.h", "mesh_2components_2wedge__tex__coords_8h.html", "mesh_2components_2wedge__tex__coords_8h" ]
];