var group__face__components =
[
    [ "vcl::face::HasAdjacentEdges", "conceptvcl_1_1face_1_1HasAdjacentEdges.html", null ],
    [ "vcl::face::HasOptionalAdjacentEdges", "conceptvcl_1_1face_1_1HasOptionalAdjacentEdges.html", null ],
    [ "vcl::face::HasAdjacentFaces", "conceptvcl_1_1face_1_1HasAdjacentFaces.html", null ],
    [ "vcl::face::HasOptionalAdjacentFaces", "conceptvcl_1_1face_1_1HasOptionalAdjacentFaces.html", null ],
    [ "vcl::face::HasBitFlags", "conceptvcl_1_1face_1_1HasBitFlags.html", null ],
    [ "vcl::face::HasColor", "conceptvcl_1_1face_1_1HasColor.html", null ],
    [ "vcl::face::HasOptionalColor", "conceptvcl_1_1face_1_1HasOptionalColor.html", null ],
    [ "vcl::face::HasCustomComponents", "conceptvcl_1_1face_1_1HasCustomComponents.html", null ],
    [ "vcl::face::HasFaceBitFlags", "conceptvcl_1_1face_1_1HasFaceBitFlags.html", null ],
    [ "vcl::face::HasMark", "conceptvcl_1_1face_1_1HasMark.html", null ],
    [ "vcl::face::HasOptionalMark", "conceptvcl_1_1face_1_1HasOptionalMark.html", null ],
    [ "vcl::face::HasNormal", "conceptvcl_1_1face_1_1HasNormal.html", null ],
    [ "vcl::face::HasOptionalNormal", "conceptvcl_1_1face_1_1HasOptionalNormal.html", null ],
    [ "vcl::face::HasPolygonBitFlags", "conceptvcl_1_1face_1_1HasPolygonBitFlags.html", null ],
    [ "vcl::face::HasPrincipalCurvature", "conceptvcl_1_1face_1_1HasPrincipalCurvature.html", null ],
    [ "vcl::face::HasOptionalPrincipalCurvature", "conceptvcl_1_1face_1_1HasOptionalPrincipalCurvature.html", null ],
    [ "vcl::face::HasQuality", "conceptvcl_1_1face_1_1HasQuality.html", null ],
    [ "vcl::face::HasOptionalQuality", "conceptvcl_1_1face_1_1HasOptionalQuality.html", null ],
    [ "vcl::face::HasTriangleBitFlags", "conceptvcl_1_1face_1_1HasTriangleBitFlags.html", null ],
    [ "vcl::face::HasVertexReferences", "conceptvcl_1_1face_1_1HasVertexReferences.html", null ],
    [ "vcl::face::HasWedgeColors", "conceptvcl_1_1face_1_1HasWedgeColors.html", null ],
    [ "vcl::face::HasOptionalWedgeColors", "conceptvcl_1_1face_1_1HasOptionalWedgeColors.html", null ],
    [ "vcl::face::HasWedgeTexCoords", "conceptvcl_1_1face_1_1HasWedgeTexCoords.html", null ],
    [ "vcl::face::HasOptionalWedgeTexCoords", "conceptvcl_1_1face_1_1HasOptionalWedgeTexCoords.html", null ]
];